services:
  mysql-db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=mydatabase
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  jpa-app:
    depends_on:
      - mysql-db
    restart: on-failure
    image: explorecali-jpa:3.0.0
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{ "spring.datasource.url" : "jdbc:mysql://mysql-db:3306/mydatabase", "spring.datasource.username" : "root", "spring.datasource.password" : "verysecret", "spring.docker.compose.enabled": "false" }'
